module.exports = {
    Summary: "",
    DATE: "",
    Shift: "",
    Reception: "",
    Member: "",
    Nama: "",
    Kamar: "",
    Total: "",
    CHtime: "",
    Chusr: "",
    Invoice: "",
    Date_Trans: "",
    Bayar: "",
    Kembali: "",
    Number: "",
    Printed: "",
    Flag: "",
    Posted: "",
    Export: ""
};