module.exports = {
    table: "IHP_Promo_Rcp",

    Reception: "IHP_Promo_Rcp.Reception",
    Promo: "IHP_Promo_Rcp.Promo",
    Start_Promo: "IHP_Promo_Rcp.Start_Promo",
    End_promo: "IHP_Promo_Rcp.End_promo",
    Status_Promo: "IHP_Promo_Rcp.Status_Promo",
    Syarat_Kamar: "IHP_Promo_Rcp.Syarat_Kamar",
    Kamar: "IHP_Promo_Rcp.Kamar",
    Syarat_Jenis_kamar: "IHP_Promo_Rcp.Syarat_Jenis_kamar",
    Jenis_Kamar: "IHP_Promo_Rcp.Jenis_Kamar",
    Syarat_Durasi: "IHP_Promo_Rcp.Syarat_Durasi",
    Durasi: "IHP_Promo_Rcp.Durasi",
    Syarat_Hari: "IHP_Promo_Rcp.Syarat_Hari",
    Hari: "IHP_Promo_Rcp.Hari",
    Syarat_Jam: "IHP_Promo_Rcp.Syarat_Jam",
    Date_Start: "IHP_Promo_Rcp.Date_Start",
    Time_Start: "IHP_Promo_Rcp.Time_Start",
    Date_Finish: "IHP_Promo_Rcp.Date_Finish",
    Time_Finish: "IHP_Promo_Rcp.Time_Finish",
    Syarat_Quantity: "IHP_Promo_Rcp.Syarat_Quantity",
    Quantity: "IHP_Promo_Rcp.Quantity",
    Diskon_Persen: "IHP_Promo_Rcp.Diskon_Persen",
    Diskon_Rp: "IHP_Promo_Rcp.Diskon_Rp",
    Syarat_Inventory: "IHP_Promo_Rcp.Syarat_Inventory",
    Inventory: "IHP_Promo_Rcp.Inventory",
    Sign_Inventory: "IHP_Promo_Rcp.Sign_Inventory",
    Sign_Diskon_Persen: "IHP_Promo_Rcp.Sign_Diskon_Persen",
    Sign_Diskon_Rp: "IHP_Promo_Rcp.Sign_Diskon_Rp",
    FlagExtend: "IHP_Promo_Rcp.FlagExtend",

    Price: "Price"
};