module.exports = {
    table: "IHP_Room",

    Kamar: "IHP_Room.Kamar",
    Jenis_Kamar: "IHP_Room.Jenis_Kamar",
    Kapasitas: "IHP_Room.Kapasitas",
    Reception: "IHP_Room.Reception",
    Nama_Tamu: "IHP_Room.Nama_Tamu",
    Jumlah_Tamu: "IHP_Room.Jumlah_Tamu",
    Kondisi_Kamar: "IHP_Room.Kondisi_Kamar",
    CHTime: "IHP_Room.CHTime",
    CHUsr: "IHP_Room.CHUsr",
    Jam_Checkin: "IHP_Room.Jam_Checkin",
    Jam_Masuk: "IHP_Room.Jam_Masuk",
    Jam_Checkout: "IHP_Room.Jam_Checkout",
    Status_Ready: "IHP_Room.Status_Ready",
    Status_Checkin: "IHP_Room.Status_Checkin",
    Status_10: "IHP_Room.Status_10",
    Status_Reservation: "IHP_Room.Status_Reservation",
    Status_CheckOut: "IHP_Room.Status_CheckOut",
    Status_Order: "IHP_Room.Status_Order",
    IP_Address: "IHP_Room.IP_Address",
    Nama_Computer: "IHP_Room.Nama_Computer",
    Keterangan_Connect: "IHP_Room.Keterangan_Connect",
    Service_Kamar: "IHP_Room.Service_Kamar",
    Kamar_Ready : "IHP_Room.Kamar_Ready ",
    Keterangan_Tamu: "IHP_Room.Keterangan_Tamu",
    Keterangan: "IHP_Room.Keterangan",
    Status_Masuk: "IHP_Room.Status_Masuk",
    Status_Extend: "IHP_Room.Status_Extend",
    Ip_Address_Call: "IHP_Room.Ip_Address_Call",

    NReception: "Reception",
    NDurasi: "Durasi"
};