module.exports = {
    table: "IHP_Inventory",

    Inventory: "IHP_Inventory.Inventory",
    Nama: "IHP_Inventory.Nama",
    GROUP: "IHP_Inventory.GROUP",
    Weight: "IHP_Inventory.Weight",
    QMin: "IHP_Inventory.QMin",
    QOrder: "IHP_Inventory.QOrder",
    Location: "IHP_Inventory.Location",
    Unit: "IHP_Inventory.Unit",
    Price: "IHP_Inventory.Price",
    Price2: "IHP_Inventory.Price2",
    Account: "IHP_Inventory.Account",
    Status: "IHP_Inventory.Status",
    Stock: "IHP_Inventory.Stock",
    Export: "IHP_Inventory.Export",
    Picture: "IHP_Inventory.Picture",
    CHTime: "IHP_Inventory.CHTime",
    CHUsr: "IHP_Inventory.CHUsr",
    Supplier: "IHP_Inventory.Supplier",
    StrName: "IHP_Inventory.StrName",
    Service: "IHP_Inventory.Service",
    Pajak: "IHP_Inventory.Pajak",
    Point: "IHP_Inventory.Point",
    Reward: "IHP_Inventory.Reward",
    InventoryID_Global: "IHP_Inventory.InventoryID_Global",
    Olahan: "IHP_Inventory.Olahan"
};